version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: projectvprofile/webapp:V1
    ports:
      - "90:80"
    container_name: webapp
    volumes:
      - webfiles:/var/www/html/

volumes:
  webfiles:

